// layout.js
import './layout.css'

// pulls in global styles and sets up the root layout for the app
// import "./globals.css"
import Nav from "./Nav"

export const metadata = {
  title: "Crochet Order App",
  description: "Generated by Monalisa Sabina",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
         <div>
            <Nav />
            <main> {children}</main>
         </div>
      </body>
    </html>
  )
}

