// app/layout.js
import './layout.css';
import Nav from "./Nav";

export const metadata = {
  title: "Crochet Order App",
  description: "Generated by Monalisa Sabina",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main>{children}</main>
      </body>
    </html>
  );
}